Server:
  Domain: 'localhost:8080'
  Addr: 'localhost'
  Port: 8080
Mysql:
  Name: 'root'
  Password: 'root'
  Addr: 'localhost'
  Port: 3306
  Database: 'goMian'
Redis:
  Addr: 'localhost:6379'
  Password: 'root'
